import React, { useState } from 'react'
import { Twitter, Facebook, Instagram, Link2, Download, X } from 'lucide-react'

function ShareModal({ isOpen, onClose, isDark = false, reportData = null }) {
  const [copySuccess, setCopySuccess] = useState(false)

  if (!isOpen) return null

  const generateShareText = (platform) => {
    if (!reportData) return ""

    const { weekly, insights } = reportData
    const workoutCount = weekly.workouts.totalWorkouts
    const avgCalories = weekly.nutrition.avgCalories
    const daysTracked = weekly.nutrition.daysLogged

    let text = ""
    
    switch (platform) {
      case 'twitter':
        text = `💪 My fitness week recap:\n🏋️ ${workoutCount} workouts\n🍎 ${avgCalories} avg calories/day\n📊 ${daysTracked} days tracked\n\nStaying consistent with my health goals! #FitnessJourney #HealthyLifestyle`
        break
      case 'facebook':
        text = `Weekly fitness update! 💪\n\nThis week I completed ${workoutCount} workouts, maintained an average of ${avgCalories} calories per day, and tracked my nutrition for ${daysTracked} days.\n\n${insights.length > 0 ? insights[0].description : 'Making steady progress!'}\n\n#FitnessGoals #HealthyLiving #Consistency`
        break
      case 'instagram':
        text = `Weekly wins! 🎉\n\n💪 ${workoutCount} workouts complete\n🥗 ${avgCalories} avg cals/day\n📈 ${daysTracked} days tracked\n\nConsistency is key! 🔥\n\n#FitnessJourney #HealthyLifestyle #WeeklyWins #Motivation #FitnessGoals #HealthyLiving #Progress #Workout #Nutrition`
        break
      default:
        text = `My fitness week: ${workoutCount} workouts, ${avgCalories} avg calories/day, ${daysTracked} days tracked. Making progress on my health goals!`
    }
    
    return text
  }

  const handleShare = async (platform) => {
    const text = generateShareText(platform)
    const url = window.location.href
    
    let shareUrl = ""
    
    switch (platform) {
      case 'twitter':
        shareUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&url=${encodeURIComponent(url)}`
        break
      case 'facebook':
        shareUrl = `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}&quote=${encodeURIComponent(text)}`
        break
      case 'instagram':
        // Instagram doesn't support direct URL sharing, so we'll copy to clipboard
        await navigator.clipboard.writeText(text)
        setCopySuccess(true)
        setTimeout(() => setCopySuccess(false), 2000)
        alert('Caption copied to clipboard! Open Instagram and paste it with your fitness photo.')
        return
      default:
        return
    }
    
    window.open(shareUrl, '_blank', 'width=600,height=400')
  }

  const handleCopyLink = async () => {
    const text = generateShareText('generic')
    const fullText = `${text}\n\nCheck out my fitness progress: ${window.location.href}`
    
    try {
      await navigator.clipboard.writeText(fullText)
      setCopySuccess(true)
      setTimeout(() => setCopySuccess(false), 2000)
    } catch (err) {
      console.error('Failed to copy text: ', err)
    }
  }

  const handleDownloadReport = () => {
    if (!reportData) return

    const { weekly, monthly, insights, generatedAt } = reportData
    
    // Create a simple text report
    const reportText = `
FITNESS TREND REPORT
Generated: ${generatedAt}

=== KEY INSIGHTS ===
${insights.map(insight => `• ${insight.title}: ${insight.description}`).join('\n')}

=== THIS WEEK ===
• Average Calories/Day: ${weekly.nutrition.avgCalories}
• Workouts: ${weekly.workouts.totalWorkouts}
• Exercise Minutes: ${weekly.workouts.totalMinutes}
• Days Tracked: ${weekly.nutrition.daysLogged}

=== THIS MONTH ===
• Average Calories/Day: ${monthly.nutrition.avgCalories}
• Workouts: ${monthly.workouts.totalWorkouts}
• Exercise Minutes: ${monthly.workouts.totalMinutes}
• Days Tracked: ${monthly.nutrition.daysLogged}

---
Generated by Network School Fitness Tracker
    `.trim()

    const blob = new Blob([reportText], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `fitness-report-${new Date().toISOString().split('T')[0]}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <div style={{
      position: 'fixed',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 1000
    }}>
      <div style={{
        backgroundColor: isDark ? 'black' : 'white',
        border: `2px solid ${isDark ? 'white' : 'black'}`,
        padding: '32px',
        maxWidth: '500px',
        width: '90%',
        maxHeight: '90vh',
        overflowY: 'auto'
      }}>
        <div style={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          marginBottom: '24px'
        }}>
          <h2 style={{
            fontSize: '24px',
            fontWeight: 'bold',
            color: isDark ? 'white' : 'black',
            margin: 0,
            fontFamily: 'Georgia, "Times New Roman", Times, serif'
          }}>
            Share Your Progress
          </h2>
          <button
            onClick={onClose}
            style={{
              background: 'none',
              border: 'none',
              fontSize: '24px',
              cursor: 'pointer',
              color: isDark ? 'white' : 'black'
            }}
          >
            <X size={24} />
          </button>
        </div>

        <div style={{
          marginBottom: '24px',
          padding: '16px',
          border: `1px solid ${isDark ? '#333' : '#e5e5e5'}`,
          backgroundColor: isDark ? '#111' : '#f9f9f9'
        }}>
          <div style={{
            fontSize: '14px',
            color: isDark ? '#a3a3a3' : '#6b7280',
            marginBottom: '8px',
            fontFamily: 'system-ui, -apple-system, sans-serif'
          }}>
            Preview:
          </div>
          <div style={{
            fontSize: '14px',
            color: isDark ? 'white' : 'black',
            fontFamily: 'system-ui, -apple-system, sans-serif',
            whiteSpace: 'pre-line'
          }}>
            {generateShareText('generic')}
          </div>
        </div>

        {/* Social Media Buttons */}
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(2, 1fr)',
          gap: '16px',
          marginBottom: '24px'
        }}>
          <button
            onClick={() => handleShare('twitter')}
            style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              gap: '8px',
              padding: '16px',
              border: `2px solid #1DA1F2`,
              backgroundColor: isDark ? 'black' : 'white',
              color: '#1DA1F2',
              fontSize: '14px',
              fontWeight: 'bold',
              cursor: 'pointer',
              fontFamily: 'system-ui, -apple-system, sans-serif'
            }}
          >
            <Twitter size={16} />
            Twitter
          </button>

          <button
            onClick={() => handleShare('facebook')}
            style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              gap: '8px',
              padding: '16px',
              border: `2px solid #4267B2`,
              backgroundColor: isDark ? 'black' : 'white',
              color: '#4267B2',
              fontSize: '14px',
              fontWeight: 'bold',
              cursor: 'pointer',
              fontFamily: 'system-ui, -apple-system, sans-serif'
            }}
          >
            <Facebook size={16} />
            Facebook
          </button>

          <button
            onClick={() => handleShare('instagram')}
            style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              gap: '8px',
              padding: '16px',
              border: `2px solid #E4405F`,
              backgroundColor: isDark ? 'black' : 'white',
              color: '#E4405F',
              fontSize: '14px',
              fontWeight: 'bold',
              cursor: 'pointer',
              fontFamily: 'system-ui, -apple-system, sans-serif'
            }}
          >
            <Instagram size={16} />
            Instagram
          </button>

          <button
            onClick={handleCopyLink}
            style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              gap: '8px',
              padding: '16px',
              border: `2px solid ${isDark ? 'white' : 'black'}`,
              backgroundColor: isDark ? 'black' : 'white',
              color: isDark ? 'white' : 'black',
              fontSize: '14px',
              fontWeight: 'bold',
              cursor: 'pointer',
              fontFamily: 'system-ui, -apple-system, sans-serif'
            }}
          >
            <Link2 size={16} />
            {copySuccess ? 'Copied!' : 'Copy Link'}
          </button>
        </div>

        {/* Download Report */}
        <button
          onClick={handleDownloadReport}
          style={{
            width: '100%',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            gap: '8px',
            padding: '16px',
            border: `2px solid ${isDark ? 'white' : 'black'}`,
            backgroundColor: isDark ? 'white' : 'black',
            color: isDark ? 'black' : 'white',
            fontSize: '16px',
            fontWeight: 'bold',
            cursor: 'pointer',
            fontFamily: 'system-ui, -apple-system, sans-serif'
          }}
        >
          <Download size={16} />
          Download Full Report
        </button>

        <div style={{
          marginTop: '16px',
          fontSize: '12px',
          color: isDark ? '#666' : '#999',
          textAlign: 'center',
          fontFamily: 'system-ui, -apple-system, sans-serif'
        }}>
          Share your fitness journey and inspire others! 💪
        </div>
      </div>
    </div>
  )
}

export default ShareModal
